### ISSUE TITLE
Motivate collaborators to change their membership visibility?

### ISSUE THREAD

**Issue by JohannesLipp** [International-Data-Spaces-Association/idsa#1]
It might be a great idea in terms of public visibility and transparency to ask our collaborators to make their affiliation with IDSA on GitHub public.
That is the [IDSA People Page](https://github.com/orgs/International-Data-Spaces-Association/people). The task here is to contact the people and ask them to change the visibility, cf. the screenshot below.

![image](https://user-images.githubusercontent.com/15930331/92459358-df46d000-f1c6-11ea-998a-e4182c6e42b9.png)

**Comment by anilturkmayali** [comment]
Thank you very much for sharing this suggestion @JohannesLipp 
An email requesting for support in this issue has been shared with all collaborators of IDSA Open Source Landscape. 
Collaboration is expected to happen, hopefully on a high level :) 

Thank you, 
Best regards,  
Anil
