### ISSUE TITLE
Inviting and tagging people for the "IDS documentation (StarterKit4.0)

### ISSUE THREAD

**Issue by aliasimon** [International-Data-Spaces-Association/idsa#10]
Hi @anilturkmayali and @ssteinbuss , 

I can oly add/tag people to the "[IDS Documentation](https://github.com/International-Data-Spaces-Association/idsa/blob/documentation-IDS/documentation/README.md)" if they are member of the IDSA (here in Git-Hub). 
Those who are not member cannot even see the document (as SQS experienced for example). 

Do you know, how to fix this? - maybe we need to put the "IDS Documentation" to the main branch? Or do we need to add everyone to the IDSA? 

BR, 
Natalia

**Comment by ssteinbuss** [comment]
Hi @aliasimon ,
three  different things here:
1. the repository is public, so everyone is able to see the document. Doesn't matter if in a branch or in the master/main. 
2. to contribute, you require access rights. 
3. to collaborate is easier, if people are member of the IDSA org. 

Let's fix this.

**Comment by aliasimon** [comment]
Fixed: Use [this form](https://forms.office.com/r/JhH7HpCcGG) to become part of the IDSA organisation on GitHub.
