### ISSUE TITLE
Combine "Gather Knowledge" with "User Journey" and "Starter Kit" - Content Change Request

### ISSUE THREAD

**Issue by DomenicFranke** [International-Data-Spaces-Association/idsa#108]
**Which part of the repository is your change request related to?**
https://github.com/International-Data-Spaces-Association/idsa/blob/main/how-to-build-data-spaces/1-Gather-Knowledge.md

**Please describe which content you would expect here and tell us how to solve this request**
Under consideration of the outdated files of the IDS Starter Kit (https://industrialdataspace.jiveon.com/docs/DOC-2271) and the IDSA User Journey for Developers - Resource List (https://industrialdataspace.jiveon.com/docs/DOC-3582), the goal is to define which documents and information to look at step by step to gather all important knowledge. We want to make the path of learning as easy as possible and create a complete basis in a reasonable order.

**Can you already provide any alternative (or updated) content that can/should replace the existing content?**
The repository "Gather Knowledge" should be considered as the foundation and be build upon.

**Comment by anilturkmayali** [comment]
These changes have been reflected in the new version of the "How to Build Data Spaces?" chapter.
