### ISSUE TITLE
Chapter on "Prepare for Certification"

### ISSUE THREAD

**Issue by aliasimon** [International-Data-Spaces-Association/idsa#11]
Dear @aitorce,

as discussed, please feel free to edit the section [Prepare for Certification](https://github.com/International-Data-Spaces-Association/idsa/blob/documentation-IDS/documentation/README.md#prepare-for-certification). 

Thank you for your support!

**Comment by anilturkmayali** [comment]
As the names of the chapters (and the URLs) are changed, this issue will be closed.
