### ISSUE TITLE
Broken Link from github

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/idsa#110]
**Which part of the repository is your change request related to?**
Link from gitbook to github is broken. We have to fix it.

**Please describe which content you would expect here and tell us how to solve this request**
In the gitbook there is on the right a link "Edit on github" This leads to a wrong page, here https://github.com/Arian-IDSA/idsa/blob/main/README.md 
I would expect to get directed to the IDSA repo directly to work on it. 

**Can you already provide any alternative (or updated) content that can/should replace the existing content?**
Use the link https://github.com/International-Data-Spaces-Association/idsa/blob/main/how-to-build-data-spaces/README.md

**Additional notes**
No additional notes

**Comment by ssteinbuss** [comment]
@anilturkmayali do we need to operate on a fork? Can't we use the main branch from this repo directly?

**Comment by anilturkmayali** [comment]
@ssteinbuss yes we can connect it to the main branch. Will do it and ensure that it doesn't affect anything badly.

**Comment by anilturkmayali** [comment]
@ssteinbuss Corrected. Now we have a branch called [docs.internationaldataspaces.org](https://github.com/International-Data-Spaces-Association/idsa/tree/docs.internationaldataspaces.org) that is fully synced with the content on Gitbook. Whenever you click on the content on Gitbook, you are directly taken into that branch on Github.
