### ISSUE TITLE
Section "Develop your Components"

### ISSUE THREAD

**Issue by aliasimon** [International-Data-Spaces-Association/idsa#12]
Dear @mkollenstart 
as discussed, please feel free to add you input in the chapter [Develop your Components](https://github.com/International-Data-Spaces-Association/idsa/blob/documentation-IDS/documentation/README.md#develop-your-components). 

Thank you for your support!

**Comment by anilturkmayali** [comment]
As the names of the chapters (and the URLs) are changed, this issue will be closed.
