### ISSUE TITLE
Deadlinks from the Gitbook

### ISSUE THREAD

**Issue by TonusPlus** [International-Data-Spaces-Association/idsa#121]
**Which part of the repository is your change request related to?**
[Gitbook Step 1](https://docs.internationaldataspaces.org/knowledge-base/readme/1-gather-knowledge)

**Please describe which content you would expect here and tell us how to solve this request**
Update the link of the glossary in step 1
Update the link of the use case brochure with the latest one available in step 1

**Can you already provide any alternative (or updated) content that can/should replace the existing content?**
/

**Additional notes**
/

**Comment by anilturkmayali** [comment]
Thank you again and again @TonusPlus. This is corrected by providing link to the latest version and by linking to the "Most Important Documents" page saying that one can find the previous versions there.
