### ISSUE TITLE
Update Gitbook Step 2

### ISSUE THREAD

**Issue by TonusPlus** [International-Data-Spaces-Association/idsa#122]
**Which part of the repository is your change request related to?**
[Gitbook Step 2](https://docs.internationaldataspaces.org/knowledge-base/readme/2-define-your-use-case)

**Please describe which content you would expect here and tell us how to solve this request**
Update link of the RAM version

**Can you already provide any alternative (or updated) content that can/should replace the existing content?**
/

**Additional notes**
/

**Comment by anilturkmayali** [comment]
Thank you very much @TonusPlus this is corrected.
