### ISSUE TITLE
Update Step 3 Gitbook

### ISSUE THREAD

**Issue by TonusPlus** [International-Data-Spaces-Association/idsa#123]
**Which part of the repository is your change request related to?**
[Gitbook Step 3](https://docs.internationaldataspaces.org/knowledge-base/readme/3-build-components)

**Please describe which content you would expect here and tell us how to solve this request**
Link for deployment scenarios is missing (and written in future tense)

**Can you already provide any alternative (or updated) content that can/should replace the existing content?**
/

**Additional notes**
/

**Comment by anilturkmayali** [comment]
Thank you again @TonusPlus the link is added and the explanation corrected.
