### ISSUE TITLE
Content Change Request

### ISSUE THREAD

**Issue by wim84** [International-Data-Spaces-Association/idsa#129]
Concerning https://github.com/International-Data-Spaces-Association/idsa/blob/0910502c4abf4cd8d47004571474879919d11e43/.gitbook/assets/MVDS-Testbed_1.0.png

Connector B is described as "acting as Data Provider".
Shouldn't this be "acting as Data Consumer"?

**Comment by anilturkmayali** [comment]
Hi @wim84, 
Thank you for bringing this up. I agree with this and would like to go ahead and apply this change. 

We created a pull request out of this you can track it [here](https://github.com/International-Data-Spaces-Association/IDS-testbed)

If this will be approved by the IDS-Testbed group, we will be also replacing the image on the docs.internationaldataspaces.org 

Thank you
