### ISSUE TITLE
IDS Documentation / StarterKit4.0

### ISSUE THREAD

**Issue by aliasimon** [International-Data-Spaces-Association/idsa#13]
Hi @Brandstaedter and @hosseinzadeha, 

as discussed please find here the [document](https://github.com/International-Data-Spaces-Association/idsa/tree/documentation-IDS/documentation) that we would like to enrich until the IDSA Summit (June 22 and 23). 
Feel free to add any content that may help others in developing / implementing components at any stage. 

Thank you!

**Comment by anilturkmayali** [comment]
As the names of the chapters (and the URLs) are changed for the Knowledge Base, this issue will be closed.
