### ISSUE TITLE
IDSA Connector API Specification 

### ISSUE THREAD

**Issue by raj-ritu17** [International-Data-Spaces-Association/idsa#136]
Hello Team,

I would like to follow IDS core principle and trying to build a dataspace connector. Please, point me me to the standard Specification documentation for building API's of connector; so that I can use IDS data-space and my connector will be interoperable.

Thanks
Ritu

**Comment by anilturkmayali** [comment]
Hello @raj-ritu17 
Thank you for creating this issue. 

1) To build a connector from scratch, you can request the criteria catalogue [via this page on IDSA website](https://internationaldataspaces.org/publications/white-papers/). 
You can also check [IDS-G](https://github.com/International-Data-Spaces-Association/IDS-G) to see specifications for other IDS components. 

2) To ensure the component behaviour or the interoperability with other components you can feel free to use [IDS Testbed](https://github.com/International-Data-Spaces-Association/IDS-testbed).

If you decide to reuse the existing components, you can also check the available data connectors via the [Data Connector Report ](https://internationaldataspaces.org/data-connector-report/)

Of course, you can always refer to the projects (component or framework implementations) [available here on IDS Github](https://github.com/International-Data-Spaces-Association), to support your project. 

I hope this helps, please feel free to reach out to us anytime (or create issues in the repositories in which you are interested in) if you need further help.

**Comment by raj-ritu17** [comment]
Hello @anilturkmayali 

Thank you so much for sharing the important information !
I was trying to follow the [IDS-G](https://github.com/International-Data-Spaces-Association/IDS-G) to see specification such as [Connector and Broker Criteria Catalogue](https://industrialdataspace.jiveon.com/docs/DOC-3823), [Connector REST interaction](https://github.com/International-Data-Spaces-Association/IDS-G/blob/main/Components/Connector) and [Connector Communication](https://github.com/International-Data-Spaces-Association/IDS-G/blob/main/Components/Connector) but it gives me empty pages. 

Such as for each link it just open this page: 
![image](https://github.com/International-Data-Spaces-Association/idsa/assets/110594625/2806ac99-2433-4e29-ba52-c69e98a9594b)

So, We would like to know through which code specification we can build our REST api endpoint and their structure. So that, return values of those api should be according to IDSA rules and spec.

Thank you in advance for your support.
Any guidelines would be greatly appreciated.

**Comment by anilturkmayali** [comment]
Thank you @raj-ritu17 for this issue, 
The content on IDS-G are currently under development. As I've mentioned before, you can request the criteria catalogue, 
and especially regarding the part for API development, you may also refer to [Dataspace Protocol available via ids-specification repository](https://github.com/International-Data-Spaces-Association/ids-specification)

A rendered version of it is also available [here](https://docs.internationaldataspaces.org/dataspace-protocol/overview/readme).

In case you have any questions about the Dataspace Protocol, you are warmly invited to create an issue there. 

Hope this helps,
Thank you
