### ISSUE TITLE
Correct broken links

### ISSUE THREAD

**Issue by JnIgSnBr** [International-Data-Spaces-Association/idsa#138]
**Which part of the repository is your change request related to?**
../International-Data-Spaces-Association/idsa/blob/main/how-to-build-data-spaces/README.md
![broken links_2023-07-07 103948](https://github.com/International-Data-Spaces-Association/idsa/assets/138658520/d8180832-79f1-4699-ab58-9157145c540f)

**Please describe which content you would expect here and tell us how to solve this request**
The file identified in the previous section contained broken links. Those are:
a) href="/how-to-build-data-spaces/2-Define-Your-Use-Case.md". I suppose it should be href="/how-to-build-data-spaces/2_Define-Your-Use-Case.md"
b) href="/how-to-build-data-spaces/3-Build-Components.md". I suppose it should be href="/how-to-build-data-spaces/3_Build-Components.md"
c) href="/how-to-build-data-spaces/4-Prepare-for-Go-Live.m". I suppose it should be href="/how-to-build-data-spaces/4_Prepare-for-Go-Live.m"
d) href="/how-to-build-data-spaces/5-Share.md". I suppose it should be href="/how-to-build-data-spaces/5_Share.md"

**Can you already provide any alternative (or updated) content that can/should replace the existing content?**
Go directly to the files without using links

**Additional notes**
N/A

**Comment by anilturkmayali** [comment]
Thank you @JnIgSnBr for notifying us about this bug. It is corrected.

**Comment by JnIgSnBr** [comment]
¡A vosotros por la rapidez!.

Revisado el cambio realizado se observa que:
a) href="/how-to-build-data-spaces/4_Prepare-for-Go-Live.md" necesitaría referenciar a  href="/how-to-build-data-spaces/4_Prepare for Go Live.md"
¿Es preferible abrir un nuevo problema para su corrección?.
