### ISSUE TITLE
IDS-G-pre is outdated - content has to be edited

### ISSUE THREAD

**Issue by JessicaRombs** [International-Data-Spaces-Association/idsa#142]
**Which part of the repository is your change request related to?**

- [README](https://github.com/International-Data-Spaces-Association/idsa#globe_with_meridians-ids-g-)
- [Overview on the IDS Repositories](https://github.com/International-Data-Spaces-Association/idsa/blob/main/overview_repositories.md)

**Please describe which content you would expect here and tell us how to solve this request**

Descriptions of- and links to IDS-G-pre have to be changed, as it is archived and not part of the described work anymore.

**Comment by anilturkmayali** [comment]
Done the changes on the main repository (idsa)
