### ISSUE TITLE
Docs: Add information on Dataspace Protocol to the Knowledge Base

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/idsa#143]
##Please describe the problem that you would like to solve with this feature##

The Dataspace Protocol is an important resource from IDSA and this should be promoted also in the knowledge base. 

##Describe the solution you'd like##

* Provide an anchor from the knowledge base to the Dataspace Protocol (findability)
* Provide a short abstract/knowledge snippet on the dataspace Protocol

##*Describe alternatives you've considered##

Do nothing. 

##Additional context##

...

**Comment by anilturkmayali** [comment]
Hi @ssteinbuss, 
I just noticed that we have the link on these two pages: 
https://docs.internationaldataspaces.org/ids-knowledgebase/ (main page of the KB)

and also here (3rd step of the how to build data spaces, with a short info snippet): 
https://github.com/International-Data-Spaces-Association/idsa/blob/main/how-to-build-data-spaces/3_Build-Components.md

Could you specifically mention the pages where the information should be added please? And I'll take care of that.

Thank you :)

**Comment by ssteinbuss** [comment]
Hi @anilturkmayali ,

you are right, but I was referring to this page [https://docs.internationaldataspaces.org/knowledge-base/](https://docs.internationaldataspaces.org/knowledge-base/). I would be in favor of having the DSP mentioned here, too. 

1. in the menu on the left
2. with a short text.
