### ISSUE TITLE
How can we address different Ecosystems or domains

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/idsa#15]
we might missuse the  labels for domains, e.g. mobility, energy,...

**Comment by anilturkmayali** [comment]
Hi @ssteinbuss 

I would suggest this: 
We can take the 9 domains (key sectors for data spaces) into consideration (at least in the starting phase).
- Manufacturing
- Green
- Mobility
- Health 
- Finance
- Energy
- Agriculture
- Public Administration
- Skills

In order not to mix them up with the existing labels, we can add "domain_" at the beginning of each label. 
Such as: domain_green, domain_mobility, etc. 

And we can mark each with a relevant color/tone, where it is possible, e.g. Health:Red, Energy:Yellow, Finance:Green, etc.

**Comment by ssteinbuss** [comment]
Hi @anilturkmayali ,
great idea. @aliasimon does this cover the domains the A-Team considers?

**Comment by anilturkmayali** [comment]
Hi @Christoph-IDSA, @ggiussani, @TonusPlus, @aliasimon,
Could you please check the discussion above and let us know if these suggested labels are sufficient for the domains considered by A-Team? 

Thank you,

**Comment by larsmnagel** [comment]
Hi @anilturkmayali, we should also check with the data spaces proposed in the digital europe programme. There are roughly 18 mentioned (e. g. tourism, media, cultural heritage), and there will be projects starting and funded soon. Just to think about it. Perhaps you can discuss with Antoine and make a link to the data spaces support centre proposal. Best wishes, Lars

**Comment by anilturkmayali** [comment]
Hi @larsmnagel thank you for your feedback. I discussed with @TonusPlus. 

[In the work programme document](https://ec.europa.eu/newsroom/repository/document/2021-46/C_2021_7914_1_EN_annexe_acte_autonome_cp_part1_v3_x3qnsqH6g4B4JabSGBy9UatCRc8_81099.pdf), the data spaces below are mentioned.

Green deal, Mobility, Manufacturing, Agriculture, Energy, Cultural Heritage, Health, Media, Public Administration, Public Procurement, Law enforcement, Finance, Smart Communities, Skills, Tourism, Financial, Language

These are added as labels on: [Labels page](https://github.com/International-Data-Spaces-Association/idsa/issues/labels)

Please let me know if there are any industries need to be added into the list. 

Fyi @ssteinbuss, @Christoph-IDSA @aliasimon @ggiussani
