### ISSUE TITLE
Enrich section "Setup your IDS Connector in your system landscape": Link to DSC, Trusted Connector, TRUE Connector

### ISSUE THREAD

**Issue by aliasimon** [International-Data-Spaces-Association/idsa#20]
Enrich section "Setup your IDS Connector in your system landscape with the link to DSC, Trusted Connector, TRUE Connector.

[here the link to the section](https://github.com/International-Data-Spaces-Association/idsa/blob/documentation-IDS/documentation/README.md#goals-of-the-international-data-spaces)

**Comment by anilturkmayali** [comment]
This will be taken into consideration in two ways: 
1) "how to build data spaces?" guide (if the user wants to develop a component by themselves)
2) deployment scenarios (if the user wants to use one of the existing building blocks)
