### ISSUE TITLE
Enrich section "Design your architecture"

### ISSUE THREAD

**Issue by aliasimon** [International-Data-Spaces-Association/idsa#23]
Enrich the section  [Design your architecture](https://github.com/International-Data-Spaces-Association/idsa/blob/documentation-IDS/documentation/README.md#design-your-architecture)
This section is about how to design your architecture of your component. It should provide the most important links and a short guidance on how to apply them. 
Please think about the following points while adding them: 
- Why are you adding them? (Why is it important for the architecture)
- In which stage are they important? 
- How do you recommend to apply them? 
- What are relevant links?

**Comment by anilturkmayali** [comment]
As the names of the chapters (and the URLs) are changed for the new Knowledge Base structure, this issue will be closed.
