### ISSUE TITLE
Enrich section "Develop your component - IDS Connector Architecture"

### ISSUE THREAD

**Issue by aliasimon** [International-Data-Spaces-Association/idsa#24]
Enrich section [Develop your component - IDS Connector Architecture](https://github.com/International-Data-Spaces-Association/idsa/blob/documentation-IDS/documentation/README.md#develop-your-components)

This section is about how to develop your connector. It should provide the most important links and a short guidance on how to apply them.
Please think about the following points while adding the information:
	• Why are you adding the content? (Why is it important for the building of the component.)
	• In which stage is it important?
	• How do you recommend to apply the links or the information?
	• What are relevant links?

**Comment by anilturkmayali** [comment]
This will be taken into consideration in two ways: 
1) "how to build data spaces?" guide (if the user wants to develop a component by themselves)
2) deployment scenarios (if the user wants to use one of the existing building blocks)

and will be added as separate tasks when necessary.
