### ISSUE TITLE
Integrate the data space connector documentation

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/idsa#39]
we should link this one 
https://international-data-spaces-association.github.io/DataspaceConnector/

**Comment by anilturkmayali** [comment]
Added a link to the DSC documentation on [Step 1: Gather Knowledge page of "How to Build Data Spaces?"](https://github.com/International-Data-Spaces-Association/idsa/blob/main/how-to-build-data-spaces/1-Gather-Knowledge.md). https://github.com/International-Data-Spaces-Association/idsa/blob/main/how-to-build-data-spaces/1-Gather-Knowledge.md
