### ISSUE TITLE
Provide an overview on OSS components and initatives

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/idsa#5]
We need a starting point to provide an overview of available OSS components and initiatives.

**Comment by anilturkmayali** [comment]
This page provides the information as a starting point.
https://github.com/International-Data-Spaces-Association/idsa/blob/main/documentation/3-Build-Components.md

and it will be reviewed and updated as mentioned in this issue: 
https://github.com/International-Data-Spaces-Association/idsa/issues/66
