### ISSUE TITLE
How can we explain data spaces based on the Building Blocks from the Design principles paper

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/idsa#54]
How can we explain how to build data spaces based on the Design Principles Paper?

**Comment by ssteinbuss** [comment]
Coming from the perspective of different personas that use our knowledge base I would assume that someone might ask: how can I build a data space based on the [design principles for data spaces](https://design-principles-for-data-spaces.org/). 
This should include:
- a brief description of the technical building blocks
- potential implementations for the building blocks with components like IDS Connectors and other IDS components, FIWARE components.
- Link to the required resources
- a setup guide to build a data space based on the building blocks.

Open questions:
- do we have to include the governance building blocks?

**Comment by ssteinbuss** [comment]
We might have this as a side stream for the OpenDEI TF1 iteration 2?

**Comment by ssteinbuss** [comment]
https://github.com/FIWARE/catalogue/tree/master/data-spaces

**Comment by anilturkmayali** [comment]
There is an ongoing work in this area which made great progress. 

There is the public repo [Open DEI Building Blocks](https://github.com/International-Data-Spaces-Association/OPENDEI-Building-Blocks) with limited information.

There is also a [private repository](https://github.com/International-Data-Spaces-Association/Building-Blocks-Catalog) where there is a great amount of content. When the work in this private repo will be finalized, the content will be transferred to the public repository as soon as the consent (by the consortium members) is granted.

I am closing this issue now but if you think this should remain open then it might be better to transfer this to [Open DEI Building Blocks repository](https://github.com/International-Data-Spaces-Association/OPENDEI-Building-Blocks).

For your information & consideration,
@ssteinbuss @SilviaIDSA @silviaarellanogarcia
