### ISSUE TITLE
Getting started documentation for IDS(A)

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/idsa#6]
The Starter Kit (1,2,3) are depracted. We need to broaden the perspective and provide comprehensive documentation for IDS starters.

**Comment by ssteinbuss** [comment]
Please start in this branch https://github.com/International-Data-Spaces-Association/idsa/tree/IDS-documentation

**Comment by aliasimon** [comment]
Added sections that need to be filled. [The document is here](https://github.com/International-Data-Spaces-Association/idsa/blob/documentation-IDS/documentation/README.md)

**Comment by anilturkmayali** [comment]
Now we have the section "how to build data spaces?" which covers this need. 
We can create new specific issues for enrichment of specific sections and link it to the [IDS Knowledge Base](https://github.com/International-Data-Spaces-Association/idsa/projects/3) project.
