### ISSUE TITLE
MVDS explanation and Deployment examples

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/idsa#60]
we have to explain this and then get it started

**Comment by ssteinbuss** [comment]
PR #82 added the requested page. Can we close this issue now? I have some open points:
- After having the definition on the page, do we need an additional repository for the MVDS, or do we link from here?
- The page and its resources should go into its own folder. We should keep the root dir free from content, just structure here. The content should get in dedicated places. 
- The Deployment scenarios are directly related to this. Where do we describe those?

@anilturkmayali shall we close here and create the points above in new issues?

**Comment by anilturkmayali** [comment]
@ssteinbuss I agree with closing this issue. I will create a new one for adding Deployment Scenarios.

Regarding the first bullet point, we can current populate its content in a folder under main repo, and then think about having its own repository in the future, if needed.

The content about MVDS has been moved [its own directory](https://github.com/International-Data-Spaces-Association/idsa/tree/main/MVDS). So the second bullet point is resolved.
