### ISSUE TITLE
Provide additional resources for public reuse?

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/idsa#73]
Hi IDSA,
to support the knowledge transfer and dissemination of the IDSA activities here, we might consider providing some important slides via this repository. They could be added as pdf here in the repository or link to other places, too. This could be extended with other relevant resources. At the same time, we should not double the resources provided via the [IDSA homepage](https://www.internationaldataspaces.org). Practically speaking: 
- we could start with a pdf version of the Graduation scheme. 
- Is there a short slide deck on the How to build data spaces?

**Comment by ssteinbuss** [comment]
Still missing something on the How to.

**Comment by anilturkmayali** [comment]
@Christoph-IDSA The only missing thing to close this issue is the slide deck on How to Build Data Spaces? Maybe we can create a slide deck out of the presentation you have made with Markos, during the IDSA Winter Days? That was perfectly explaining the issue.

Thank you,

**Comment by ssteinbuss** [comment]
@anilturkmayali @Christoph-IDSA  is this already closed or still pending?

**Comment by anilturkmayali** [comment]
@ssteinbuss @Christoph-IDSA  We have the first one (pdf version of Graduation Scheme). 
But we don't have a slide deck for "How to Build Data Spaces?". If this document is available, we can close this issue. 
Fyi
