### ISSUE TITLE
"How to Build Data Spaces?" (Step 1, Gather Knowledge) Review and reorganize the page

### ISSUE THREAD

**Issue by anilturkmayali** [International-Data-Spaces-Association/idsa#88]
Review and reorganize the page with the content on: 
- Available Documentation
- Trainings, Open Consultation Hours
- Events on testing components, plugfest, hackathons,etc.

**Comment by Arian-IDSA** [comment]
Closed

**Comment by Arian-IDSA** [comment]
@anilturkmayali Do you think it makes sense to merge with #85 ?

**Comment by anilturkmayali** [comment]
@Arian-IDSA Thank you! Yes it makes more sense to close this item along with #85, as the discussions around IDS Academy are going on.
