### ISSUE TITLE
IDS Documentation / Former StarterKit4.0 your comments and views

### ISSUE THREAD

**Issue by aliasimon** [International-Data-Spaces-Association/idsa#9]
Hi there,
as discussed, I have shifted the work of the "StarterKit4.0" to GitHub, so that we can work on a living document. 
[Here the document itself](https://github.com/International-Data-Spaces-Association/idsa/blob/documentation-IDS/documentation/CONTRIBUTING.md)
Please provide me feedback on the structure - is something missing? What do you think about it? 
@HeinrichPet 
Thank you!

**Comment by anilturkmayali** [comment]
As the names of the chapters (and the URLs) are changed for the new Knowledge Base structure, this issue will be closed.
